# Generated by Django 2.2.2 on 2019-07-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Add', models.CharField(max_length=20)),
                ('MobileNo', models.IntegerField()),
                ('EmailId', models.CharField(max_length=20)),
            ],
        ),
    ]
